INSERT INTO user_details(ID, NAME, BIRTH_DATE)
VALUES(10001, 'SOO', CURRENT_DATE());

INSERT INTO user_details(ID, NAME, BIRTH_DATE)
VALUES(10002, 'DOO', CURRENT_DATE());

INSERT INTO user_details(ID, NAME, BIRTH_DATE)
VALUES(10003, 'LOO', CURRENT_DATE());